name: Build Examples

on:
  push:
    branches: [main]
    paths:
      - 'examples/**'
      - 'otel-extension/**'
      - 'lib/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
      - '.github/workflows/examples.yml'
  pull_request:
    branches: [main]
    paths:
      - 'examples/**'
      - 'otel-extension/**'
      - 'lib/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'settings.gradle'
      - '.github/workflows/examples.yml'

permissions:
  contents: read

jobs:
  build-examples:
    runs-on: ubuntu-x64-small
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          persist-credentials: false

      - name: Build otel-extension example Docker image
        run: |
          docker build \
            -f examples/with-otel-extension/Dockerfile \
            -t otel-extension-example:ci \
            .

      - name: Build otel-library example Docker image
        run: |
          docker build \
            -f examples/with-otel-library/Dockerfile \
            -t otel-library-example:ci \
            .

      - name: Build otel-extension-manual-start example Docker image
        run: |
          docker build \
            -f examples/with-otel-extension-manual-start/Dockerfile \
            -t otel-extension-manual-start-example:ci \
            .
